name: Check Company Name
on: [push]

jobs:
  check-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check if Company exists
        run: |
          grep "Company" profile.txt
          grep "Co" profile.txt